### ISSUE TITLE
大佬　请问有项目的demo或者运行后的截图吗？

### ISSUE THREAD

**Issue by Yakumo-Yukari** [D-Pow/anime-atsume#1]
是和soman差不多吗？

**Comment by D-Pow** [comment]
Hi @Yakumo-Yukari, I don't have a demo to show, but it would be worthwhile to improve the ReadMe with screenshots. Good suggestion!

Edit: Improve wording

**Comment by Yakumo-Yukari** [comment]
> Hi @Yakumo-Yukari, I don't have a demo to show, but it would be worthwhile to improve the ReadMe with screenshots. Good suggestion!
> 
> Edit: Improve wording

Cool, thank you.
